descricao_colunas = {
    "time(ms)": "Tempo desde o início da gravação (ms)",
    "ENGI_IDLE": "Motor em marcha lenta (1 = Sim, 0 = Não)",
    "IC_SPDMTR(km/h)": "Velocidade registrada no painel",
    "VSS(km/h)": "Velocidade do sensor de roda",
    "RPM(1/min)": "Rotações por minuto do motor",
    "ODOMETER(km)": "Odômetro total (km)",
    "TRIP_ODOM(km)": "Odômetro parcial (km percorridos na viagem)",
    "DSDRPM(1/min)": "RPM desejado pela ECU",
    "BOO_ABS": "Pedal do freio pressionado",
    "AF_RATIO(:1)": "Razão ar/combustível",
    "SHRTFT1(%)": "Correção de combustível em curto prazo",
    "LONGFT1(%)": "Correção de combustível em longo prazo",
    "FUELPW(ms)": "Tempo de injeção de combustível",
    "FUELLVL(%)": "Nível de combustível no tanque",
    "LOAD.OBDII(%)": "Carga do motor (via OBDII)",
    "ECT_GAUGE(Â°C)": "Temperatura do motor no painel",
    "IAT(Â°C)": "Temperatura do ar admitido",
    "O2S11_V(V)": "Tensão do sensor de oxigênio",
    "LMD_EGO1(:1)": "Leitura lambda estimada",
    "OPENLOOP": "Sistema de injeção em malha aberta (sem correção por sonda)",
    "MAP.OBDII(kPa)": "Pressão absoluta do coletor (OBDII)",
    "BARO(kPa)": "Pressão atmosférica",
    "TP.OBDII(%)": "Posição da borboleta do acelerador",
    "SPARKADV(Â°)": "Avanço da ignição",
    "VBAT_1(V)": "Voltagem da bateria",
    "AF_LEARN": "Aprendizado de mistura ar/combustível",
    "ECT(Â°C)": "Temperatura real do motor",
    "ECT.OBDII(Â°C)": "Temperatura via OBDII",
    "FUEL_CONSUM": "Combustível consumido acumulado",
    "FUEL_CORR(:1)": "Correção da mistura combustível",
    "Litres_Alcohol(L)": "Álcool consumido na viagem",
    "MAP(V)": "Pressão do coletor (em volts)",
    "MAP_V(V)": "Pressão do coletor (outro sensor, em volts)",
    "SPKDUR_1(ms)": "Duração da centelha - Cilindro 1",
    "SPKDUR_2(ms)": "Duração da centelha - Cilindro 2",
    "SPKDUR_3(ms)": "Duração da centelha - Cilindro 3",
    "SPKDUR_4(ms)": "Duração da centelha - Cilindro 4",
    "ENG_STATUS": "Status geral do motor",
    "LAMBDA_1": "Leitura da sonda lambda",
    "MIXCNT_STAT": "Status da mistura"
}
